# Generated by Django 5.1.4 on 2025-01-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='icono',
            field=models.CharField(blank=True, help_text="Inserta la clase del ícono de Font Awesome, por ejemplo: 'fa-solid fa-code'.", max_length=50, null=True),
        ),
    ]
