# Generated by Django 5.1.4 on 2025-01-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/videos/'),
        ),
    ]
