# Generated by Django 5.1.4 on 2025-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_proyecto_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='video',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='iconos',
            field=models.CharField(blank=True, help_text="Lista de iconos separados por comas, ej: 'fa-html5,fa-bootstrap,fa-js'", max_length=255, null=True),
        ),
    ]
