# Generated by Django 5.1.4 on 2025-01-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_remove_proyecto_icono_remove_proyecto_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='iconos',
        ),
    ]
