# Generated by Django 5.1.4 on 2025-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_remove_proyecto_iconos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='iconos',
            field=models.CharField(blank=True, help_text="'fa-brands fa-html5, fa-brands fa-bootstrap, fa-brands fa-js, fa-brands fa-python, fa-solid fa-database, fa-solid fa-gamepad'", max_length=255, null=True),
        ),
    ]
